resources:
- name: dummy-golang-project-github
  type: git
  source:
    branch: master
    uri: https://github.com/rms1000watt/dummy-golang-project.git

- name: dummy-golang-project-docker
  type: docker-image
  source:
    email: rms1000watt@gmail.com
    username: rms1000watt
    password: 
    repository: rms1000watt/dummy-golang-project

jobs:
- name: build-dummy-golang-project
  plan:
  - get: dummy-golang-project-github
  - put: dummy-golang-project-docker
    params:
      build: dummy-golang-project-github
      build_args:
        GOLANG_DOCKER_VERSION: 1.9.2-alpine3.7
