resources:
- name: dummy-golang-project-github
  type: git
  source:
    branch: master
    uri: https://github.com/rms1000watt/dummy-golang-project.git

jobs:
- name: build-dummy-golang-project
  plan:
  - get: dummy-golang-project-github
  - task: build-and-push
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          # repository: ubuntu
          # tag: 16.04
          repository: docker
          tag: 17.12.0-ce
      inputs:
      - name: dummy-golang-project-github
      # run:
      #   path: bash
      #   args:
      #     - -exc
      #     - |
      #       apt-get update
      #       apt-get install make -y
      #       cd dummy-golang-project-github
      #       make
      #       echo "docker push here maybe"
      run:
        path: sh
        args:
          - -exc
          - |
            apk add --update make
            cd dummy-golang-project-github
            make
            echo "docker push here maybe"
